obj-y 	+=display.o
display-objs=vout_notify.o  vout_serve.o



obj-$(CONFIG_AM_TV_OUTPUT)  += am_tvout.o
am_tvout-objs :=   tvoutc.o  tvconf.o 

obj-$(CONFIG_AM_TCON_OUTPUT)  += tcon.o

obj-$(CONFIG_AML_TCON_T13)  += t13.o

obj-$(CONFIG_AML_TCON_ML10)  += ml10.o

obj-$(CONFIG_AML_TCON_W10)  += w10.o

obj-$(CONFIG_AML_TCON_W7)  += w7.o

obj-$(CONFIG_AML_TCON_W8)  += w8.o

obj-$(CONFIG_AML_TCON_P7)  += p7.o

obj-$(CONFIG_AML_TCON_K7)  += k7.o

obj-$(CONFIG_AML_TCON_C7)  += c7.o

obj-$(CONFIG_AML_TCON_K8)  += k8.o

obj-$(CONFIG_AML_TCON_G7)  += g7.o

obj-$(CONFIG_AML_TCON_R10)  += r10.o

obj-$(CONFIG_AML_TCON_REFB13)  += refb13.o

obj-$(CONFIG_AML_TCON_K7New)  += k14.o

#EXTRA_CFLAGS += -DCONFIG_PM

